title:   JANCARLO JAMS
logo: /TP1/Perfil circular.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
<h1 align="center">HI I'M <a href="https://beacons.ai/data_jams">JANCARLO JAMS</a> </h1>
